syslog-ng/doc

- _doc/admin-guide/README.md
- _doc/dev-guide/README.md
- _doc/dev-guide/chapter_0/README.md
- _doc/dev-guide/chapter_1/README.md
- _doc/dev-guide/chapter_2/README.md
- _doc/dev-guide/chapter_3/README.md
- _doc/dev-guide/chapter_4/README.md
- _doc/dev-guide/chapter_4/macos-testing-status/README.md
- _doc/dev-guide/chapter_4/macos-testing-status/affile/README.md
- _doc/dev-guide/chapter_4/macos-testing-status/afprog/README.md
- _doc/dev-guide/chapter_4/macos-testing-status/afsocket/README.md
- _doc/dev-guide/chapter_4/macos-testing-status/afsocket/tls-encryption/README.md
- _doc/dev-guide/chapter_4/macos-testing-status/mod-python/README.md
- _doc/dev-guide/chapter_4/macos-testing-status/system-source/README.md
- _doc/dev-guide/chapter_5/README.md
- _doc/dev-guide/chapter_6/README.md
- _doc/dev-guide/chapter_7/README.md
- _doc/dev-guide/chapter_8/README.md
- _doc/doc-guide/README.md
> Quick fix of directory permlinking

- _tools/navgen
> navgen now handles sub-title

- _includes/masthead.html
- _sass/minimal-mistakes/minimal-mistakes/_search.scss
- assets/js/_main.js
> Added a hotkey to the search button

- assets/js/custom/copy-to-clipboard.js
- assets/js/custom/navigation.js
> Code block enhancements must be applied per-content bases now as well

- Gemfile
- LICENSE.midnight
- _config.yml
- _doc/README.md
- _doc/dev-guide/chapter_6/section_5.md
- _doc/dev-guide/chapter_8/section_5.md
- assets/js/custom/navigation.js
> Do not reload the already active page if its own menu item clicked

- _config.yml
- _includes/post_pagination.html
- _sass/minimal-mistakes/minimal-mistakes/_navigation.scss
- assets/js/custom/navigation.js
> Bottom pager got a similar design to the latest gitbook navigators

- _includes/post_pagination.html
- _sass/minimal-mistakes/minimal-mistakes/_navigation.scss
> Added a separator item between bottom pager navigators instead of manipulating margins

- _includes/post_pagination.html
igned-off-by: Hofi <hofione@gmail.com>
> Added the separator item between bottom pager navigators only if there are 2 navigators

- 404.md
- Gemfile
- _layouts/base.html
- _layouts/default.html
- assets/js/custom/navigation.js
> Added basic 404 page

- doc/_doc-guide/README.md
> Doc update according to the restructuring

- .github/workflows/jekyll.yml
Github pages build config update according to the restructuring
> Github pages build config update according to the restructuring

- assets/js/custom/navigation.js
> Still had unnecessary double content loading, fixed

- _sass/minimal-mistakes/minimal-mistakes/_search.scss
- assets/js/custom/navigation.js
> Cleared the focus from the clicked items

- _layouts/base.html
> Further changes to support multiple repos

- _js/custom/copy-to-clipboard-btn.js
- _js/custom/navigation.js
- _js/main.min.js
- _sass/minimal-mistakes/minimal-mistakes/_syntax.scss
- doc/_dev-guide/chapter_4/macos-testing-status/afmongodb.md
> The copy code button now has copied feedback

- _sass/minimal-mistakes/minimal-mistakes/_navigation.scss
- doc/_dev-guide/chapter_4/macos-testing-status/affile/file-destination-driver.md
- doc/_dev-guide/chapter_4/macos-testing-status/affile/file-source-driver.md
- doc/_dev-guide/chapter_4/macos-testing-status/affile/pipe-destination-driver.md
- doc/_dev-guide/chapter_4/macos-testing-status/affile/pipe-source-driver.md
- doc/_dev-guide/chapter_4/macos-testing-status/affile/stdin-source-driver.md
- doc/_dev-guide/chapter_4/macos-testing-status/affile/wildcard_file-source-driver.md
- doc/_dev-guide/chapter_4/macos-testing-status/afprog/program-destination-driver.md
- doc/_dev-guide/chapter_4/macos-testing-status/afprog/program-source-driver.md
- doc/_dev-guide/chapter_4/macos-testing-status/afsocket/network-destination-driver.md
- doc/_dev-guide/chapter_4/macos-testing-status/afsocket/network-source-driver.md
- doc/_dev-guide/chapter_4/macos-testing-status/afsocket/syslog-source-destination-driver.md
- doc/_dev-guide/chapter_4/macos-testing-status/afsocket/tls-encryption/using-network.md
- doc/_dev-guide/chapter_4/macos-testing-status/afsocket/tls-encryption/using-syslog.md
- doc/_dev-guide/chapter_4/macos-testing-status/afsocket/unix-dgram-source-destination-driver.md
- doc/_dev-guide/chapter_4/macos-testing-status/afsocket/unix-stream-destination-driver.md
- doc/_dev-guide/chapter_4/macos-testing-status/afsocket/unix-stream-source-driver.md
- doc/_dev-guide/chapter_4/macos-testing-status/afsql.md
- doc/_dev-guide/chapter_4/macos-testing-status/afuser.md
- doc/_dev-guide/chapter_4/macos-testing-status/elasticsearch-http.md
- doc/_dev-guide/chapter_4/macos-testing-status/http.md
- doc/_dev-guide/chapter_4/macos-testing-status/mod-python/python-destination-driver.md
- doc/_dev-guide/chapter_4/macos-testing-status/mod-python/python-fetcher-source-driver.md
- doc/_dev-guide/chapter_4/macos-testing-status/mod-python/python-source-driver.md
- doc/_dev-guide/chapter_4/macos-testing-status/pseudofile.md
- doc/_dev-guide/chapter_4/macos-testing-status/redis.md
- doc/_dev-guide/chapter_4/macos-testing-status/riemann.md
- doc/_dev-guide/chapter_4/macos-testing-status/system-source/README.md
> Sidebar navigator visualization fixes

- _data/navigation.yml
- _sass/minimal-mistakes/minimal-mistakes/_navigation.scss
- _tools/navgen
[Pager buttons are now using the common link and visited link colors](https://github.com/syslog-ng/doc/commit/7d6f6a77aecd0bb50570586a1cf4f392965ed9f4)
[Navgen is now handles symlinks](https://github.com/syslog-ng/doc/commit/2106c224e95b00c97831f342a983ede07df357ed)
> Navgen is now handles symlinks

- _config.yml
- _layouts/single.html
> Added option to hide empty page TOC via  toc_hide_empty config option

- _includes/nav_list_add
- _sass/minimal-mistakes/minimal-mistakes/_navigation.scss
- assets/css/main.scss
> Fixed sidebar navigator title/sub-title style assignement  and 0 level items style

- _data/navigation.yml
- _js/custom/custom-init.js
- _js/main.min.js
> Added quick override to lunr tokenizer to eliminate differences between cases like "option_1" and "option-1"

- _data/external_links.yml
- _data/links/admin-guide.yml
- _data/links/dev-guide.yml
- _data/links/doc-center.yml
- _data/links/doc-guide.yml
- _tools/navgen
- doc/404.md
- doc/README.md
- doc/_dev-guide/README.md
- doc/_dev-guide/chapter_0/README.md
- doc/_doc-guide/README.md
> First demo usages of the id, external_links

- _data/navigation.yml
- _includes/markdown_link
- _js/custom/navigation.js
- _js/main.min.js
- _sass/minimal-mistakes/minimal-mistakes/_navigation.scss
- doc/_dev-guide/chapter_4/macos-testing-status/README.md
> First version of a nice content preview tooltip

- _sass/minimal-mistakes/minimal-mistakes/_navigation.scss
Still far from perfect as depends on the size of the container :S
> A bit better tooltip alignment and sizing

- _config.yml
- _js/lunr/lunr-en.js
- _tools/pack
that is needed to all links behave the same way (e.g. for proper sidebar navigator functionality)
> Lunr now should present links without extension

- _includes/markdown_link
> Param typo fixed

- _js/custom/navigation.js
- _js/main.min.js
In frame loaded content how has to smooth scroll to the opened anchor point like it was clicked e.g. via the TOC menu
> Anchor link opening fix

- _data/navigation.yml
- _js/custom/navigation.js
- _js/main.min.js
- _tools/navgen
> Navgen fix for root item url generation

- _js/custom/navigation.js
- _js/main.min.js
As navbar must be changed as well in case of cross collection navigation the whole page will be loaded from now and on
> Fixed cross collection navigation

- _plugins/generate_tooltips.rb
> Tooltip now converts Markdown `` contents as well

- _plugins/generate_tooltips.rb
> Removed debug parts from tooltip gen

- _js/custom/navigation.js
- _js/main.min.js
> Window title now synced during in collection navigation too

- _plugins/generate_tooltips.rb
Also, using self written regex matcher for file names, the Dir.glob matcher is a joke
> Fixed `` handling

- _plugins/generate_tooltips.rb
> Fixed `` handling, again :S

- _plugins/generate_tooltips.rb
> Do not use `` for auto tooltip links, use dedicated new markdown like [[title]] quotation

- _plugins/generate_tooltips.rb
> Added custom id option to [[]] autolinks

- _config.yml
- _includes/markdown_link
- _plugins/generate_links.rb
- _plugins/generate_tooltips.rb
> Corrected the earlier changes around link file extensions

- _plugins/generate_tooltips.rb
> Added id matcher to tooltip generation

- _plugins/generate_tooltips.rb
> Description now can contain markdown autolink expressions

- _plugins/generate_tooltips.rb
> First draft of escaping some text parts from modifying by markdownify

- _plugins/generate_links.rb
> Added warning of duplicated ID during link generation

- _data/navigation.yml
- _plugins/generate_links.rb
- _plugins/generate_tooltips.rb
> First draft of using manual rendering for better autolink generation

- _plugins/generate_tooltips.rb
> Fixed description/subtitle rendering issues

- _js/custom/navigation.js
- _js/main.min.js
- _sass/minimal-mistakes/minimal-mistakes/_navigation.scss
> Tooltip aligned to mouse position now

- _plugins/generate_tooltips.rb
> Use multiline matching for special markdown block splitting as e.g. code blocks can span multilines

- _data/excluded_titles.yml
- _includes/page_pagination.html
- _layouts/single.html
- _plugins/generate_tooltips.rb
- excluded_titles now accepts patterns as well
- fixed link title matching in case titles spanned multiple lines
> Fixed collection pages bottom navigation

- _data/external_links.yml
- _js/custom/navigation.js
- _plugins/generate_tooltips.rb
- _tools/navgen
- doc/_doc-guide/README.md
> External links now can be used like other autolink/tooltip expressions in the [[title]], [[title|id]] format

- README.md
- _data/external_links.yml
- _data/navigation.yml
- _plugins/generate_tooltips.rb
- doc/.markdownlint.json
- doc/README.md
- doc/_dev-guide/README.md
- doc/_doc-guide/README.md
> Started to consolidate the opening pages

- README.md
- _plugins/generate_links.rb
- _plugins/generate_tooltips.rb
Inline HTML named anchors now added to know link lists and can be used for autolink/tooltip generation
> Fixed base url handling after external link handling modifications

- _data/external_links.yml
- _plugins/generate_tooltips.rb
- doc/README.md
> Fixed multiline matching in markdown blocks' splitting

- _data/external_links.yml
- _data/link_aliases.yml
- _data/navigation.yml
- _plugins/generate_tooltips.rb
- doc/_dev-guide/chapter_6/section_4.md
> Added link aliases

- .github/workflows/jekyll-gh-pages.yml
- _data/excluded_titles.yml
- _data/navigation.yml
- _tools/pack
- doc/_doc-guide/02_Tools/README.md
> Attempts to fix CI site builds

- .github/workflows/jekyll-gh-pages.yml
- README.md
- _data/excluded_titles.yml
- doc/README.md
- doc/_doc-guide/README.md
> Further consolidation of opening README pages, and some comment enhacements
